### ISSUE TITLE
push token

### ISSUE THREAD

**Issue by AurelianApet** [unicorndev99/Escare-NFT-App-v1#2]
checked the log, and it`s permission denied error.
Get push token and register, and then test again?
http://218.50.149.74:8545/apis/escare/push/swagger-ui/#/
use register push token api and resend.

**Comment by AurelianApet** [comment]
it seems to be that  fcm token you are using now is not active now, fcm denied access now.

**Comment by AurelianApet** [comment]
You must get push token from FCM when running app.

**Comment by AurelianApet** [comment]
don`t create push token in app, just getting it from FCM and register it.

**Comment by AurelianApet** [comment]
You must get push token from firebase when running app.
Don`t create push token in app, just getting it from firebase and register it.

**Comment by AurelianApet** [comment]
Use kyc server api for regsitering push token.

**Comment by unicorndev99** [comment]
Are there any screenshots?

**Comment by AurelianApet** [comment]
new doc

**Comment by DailaYoffey** [comment]
I uploaded new apk for Fcm Notification modal.
Pls send me screenshots of FCM modal.
I just made font smaller in the modal

**Comment by AurelianApet** [comment]
??

**Comment by AurelianApet** [comment]
attached screenshot

**Comment by DailaYoffey** [comment]
![image](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/136822190/e93bb45e-c8b7-40fa-9d9f-83ad5a1f2360)
1. First modal shows when receive notification
2. second modal shows when click the received notifiaction in the header of phone (not notification list of app UI).

**Comment by AurelianApet** [comment]
Now not working push when existing app.

exist app > receive push > click push > run app and login > check push detail api and show popup.
user can choose accept or decline on outputed popup > output the result.

**Comment by AurelianApet** [comment]
1. when receiving push in running app, modal shows - attached.
2. when receiving push in background, click push, not modal.

**Comment by DailaYoffey** [comment]
https://github.com/unicorndev99/Escare-NFT-App-v1/assets/136822190/e6ed6468-e050-40a7-beba-245b8fa09527

pls check this

**Comment by AurelianApet** [comment]
it`s not background.
exit app and test again.

**Comment by DailaYoffey** [comment]
pls check uploaded apk again.
and send me 2 screenshots of modal when notification received.
- receive notification (auto show when receive notification)
- click the notification when notification received.
![image](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/136822190/75f42d99-1dad-480a-b5c9-6cea961e591f)

**Comment by AurelianApet** [comment]
when showing first popup, it can`t be closed.
too long text and can`t find close button

**Comment by AurelianApet** [comment]
![2](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/46595764/0804e13b-7f79-4d65-a4c2-d506cd3902b3)
![1](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/46595764/9b988fb2-2495-48d4-8c53-a4270de51357)

**Comment by DailaYoffey** [comment]
pls test notifications after killing app using that apk.
And send me screenshots

**Comment by AurelianApet** [comment]
https://github.com/unicorndev99/Escare-NFT-App-v1/assets/46595764/c9fd80e1-8a1b-4352-9ff9-df1117666826

**Comment by DailaYoffey** [comment]
Also, Expo React native doesn't support notification handle of killed app.
So I will get push lists using the latest push message's msqInqToken. (will just refresh with push notification lists)
![image](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/136822190/eb126cd2-c790-4a77-a129-ce2ea3127c74)

Okay?

**Comment by AurelianApet** [comment]
ok

**Comment by AurelianApet** [comment]
1. install, register user and pin code - O
2. register push token - O
3. login - O 
4. when login, checkout list - O

----- while running app ----
5. Receive push - O
6. when receive push - checkout message list - O
7. when select message - checkout detail message and move to page - O
8. accept / decline - not tested yet

----- app background -----
 9.  receive push in background mode - O
 10. when clicking push, checkout push list - X 
	(sent old msgInqToken, not updated token)
 11. show detail message and accept/decline - X(can`t test)

 	----- app exiting -----
 12. push occurs - O
 13. when clicking push, login after running - O
 14. after login, checkout message list in main scene - X
	(sent request, but old msgInqToken, so no list)
 15. show detail message and accept/decline - X(can`t test)

**Comment by AurelianApet** [comment]
the last solution
- ignore msgInqToken in push data (app).
- updated api for msgInqToken (server).
- don`t send 2 requests, just send 1 requst.
