### ISSUE TITLE
Sometimes push message are not showed on the phone alarm

### ISSUE THREAD

**Issue by AurelianApet** [unicorndev99/Escare-NFT-App-v1#3]
1. Sometimes push message are not showed on the phone alarm.
2. Some fields are added on the api, so show them on ui.
3. Hide Accept/Decline button when code result is not v001.

**Comment by AurelianApet** [comment]
I can`t find any invitation from you.

**Comment by DailaYoffey** [comment]
sent

**Comment by DailaYoffey** [comment]
![image](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/136822190/16710a77-f576-4efd-b379-6cbc9aad3549)

**Comment by DailaYoffey** [comment]
apk uploaded.
Source code is pushed in the github

**Comment by blockchainFull2022** [comment]
![image](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/117472008/12b7c58f-23d6-4d2c-91d1-a1219c1c8897)

Pin register failed right now.
it worked before but doesn't work right now

**Comment by blockchainFull2022** [comment]
![image](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/117472008/f5a85dc3-f50f-4857-ac4a-d08e24d4f76e)


Where is notification object you said in the pptx?

**Comment by DailaYoffey** [comment]
![image](https://github.com/unicorndev99/Escare-NFT-App-v1/assets/136822190/b25b8e53-375e-4813-9908-7bb726bfcf18)


I can't find this notification object in the response.
Anyway, I am building again, will upload soon  (in 10mins)

**Comment by DailaYoffey** [comment]
https://expo.dev/artifacts/eas/4SDUwCEoaP76oBVHNhnRuj.apk

pls download this and use it
this version is used old style object of detail push list
